version: '3.8'
services:
  db:
    container_name: postgres-db
    image: 'postgres'
    ports:
      - '5411:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sportsdb
